[package]
name = "kutsche"
version = "0.1.0"
edition = "2021"


[dependencies]
configparser = "3.0"
lettre = "0.9"
rustls = "0.20.0"
rustls-pemfile = "1.0.0"
mailin = "0.6.0"
mail-parser = "0.4.5"

[dev-dependencies]
lettre_email = "0.9"
